"""create tables

Revision ID: 08e8b7691642
Revises: 82f2d6f7ae5d
Create Date: 2023-07-03 23:00:33.483994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e8b7691642'
down_revision = '82f2d6f7ae5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
